name: BuildImage

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    if: github.repository == 'kubesphere/ks-mcp-server'
    steps:
      - name: Prepare
        id: prepare
        run: |
          VERSION=latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Hub_Kubesphere
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
              docker.io/kubesphere/ks-mcp-server:${{ steps.prepare.outputs.version }}

